import streamlit
streamlit.title('My Parents for New Healthy Diner')
streamlit.header('Breakfast Favorites')
streamlit.header('Indian')
streamlit.text('Idly, Dosa, Vada Sambar')
streamlit.header('Continental')
streamlit.text('French Toast')
streamlit.text('🐔 Boiled Egg and Spinach Roll')
streamlit.text('Pancakes')
streamlit.header('🍌 Build Your Own Fruit Smoothie')
